### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Nelitaa** [Nelitaa/book-an-appointment-back-end#22]
**# Final group capstone: set up your Kanban board**

## Link to our GitHub project
[Link](https://github.com/users/Nelitaa/projects/9)

## Team
- @emmanuellmhango 
- @osbentech 
- @paulinagonzalezc 
- @Nelitaa 

## Screenshot of our board 
<img width="1504" alt="screenshot1" src="https://user-images.githubusercontent.com/98427585/230496993-25398b6b-b517-441c-ba68-9b3cb2b1e2ca.png">
<img width="1508" alt="screnshot2" src="https://user-images.githubusercontent.com/98427585/230497001-18c21dcb-40b2-4da9-94aa-23422467b825.png">

### Project requirements

- Join a Zoom call with your team. Only one person needs to create the board on behalf of the entire team but everybody should help during the call.
- Create an empty repository for your group project.
- Open the [GitHub project (Kanban board)](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) in your team repo (set up the same columns as in previous group projects). 
- Create cards based on [the project requirements](./business_requirements.md). Each task should be a separate card that:
    - Has a descriptive title.
    - Has the number of points in the `[Xpt]` prefix. That number should indicate the number of `points` which shows how complex the task is. **1 point = 1 hour of estimated work**. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
    - Has a description of the task.
- Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees. 
**NOTE it is ok to distribute tasks according to the skills and preferences of the team. However, the number of assigned points should be equal (+/- 5 points) for each member.**
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).
    - In its description, paste a link to your GitHub project.
    - Add a note telling the reviewer how many people there are in your team.
    - Take a screenshot of your board and add it to your issue's description (do it before each review to always have the freshest version of your board). You will need it for the final evaluation.
- Use the issue link to ask for a review. A code reviewer will leave you feedback in the issue's comment.
    - This review is not an evaluation but support for you. The better the Kanban board you prepare the more smooth your collaboration will be.

**Comment by Meltrust** [comment]
Hi @Nelitaa,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)


Congratulations! 🎉 

### To highlight

- All tasks have descriptions, have points and assignees ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Nelitaa,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Kindly, add a description to this task:

![image](https://user-images.githubusercontent.com/57421823/234042664-8362efa7-a74d-4331-b029-3e503fc9878e.png)

That way, we will meet that particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 👍 

- [ ] At the time of this review, these are the pointings for your team according to the kanban board:

@paulinagonzalezc 25
@Nelitaa 18
@emmanuellmhango 2
@osbentech 2

As you can see, the point differences are huge.  The general rule is that nobody can have more than 5 points than any other teammate.

Kindly, make it so no teammate has more than 5 points than any other, so we can meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

![image](https://user-images.githubusercontent.com/57421823/234043835-e2f3e087-9897-4272-bf55-18c55ed8e837.png)

_note:  This kanban board was approved some weeks ago.  If you are repeating, kindly leave a note about it in your description, in order to prevent confusion and perform a proper review._

_note 2: In your review request I can see that @Nelitaa is the only member of the team.  Kindly make a note about that in your PR description, and update it along your kanban board in order to reflect the correct team members if now you are working by yourself in order to prevent confusion and perform a proper review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
